table 'analytics vw_q7_balance_of_def'

	column team_name
		dataType: string
		sourceProviderType: nvarchar(255)
		summarizeBy: none
		sourceColumn: team_name

		annotation SummarizationSetBy = Automatic

	column season_id
		dataType: int64
		formatString: 0
		sourceProviderType: int
		summarizeBy: none
		sourceColumn: season_id

		annotation SummarizationSetBy = Automatic

	column 'Eficiencia de tiro'
		dataType: double
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		sourceProviderType: float
		summarizeBy: sum
		sourceColumn: Eficiencia de tiro

		annotation SummarizationSetBy = Automatic

	column 'Balones perdidos'
		dataType: double
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		sourceProviderType: float
		summarizeBy: sum
		sourceColumn: Balones perdidos

		annotation SummarizationSetBy = Automatic

	column balance_score
		dataType: double
		sourceProviderType: float
		summarizeBy: sum
		sourceColumn: balance_score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'analytics vw_q7_balance_of_def' = m
		mode: directQuery
		source =
				let
				    Origen = Sql.Databases("100.74.116.125,1433"),
				    NBA_Project = Origen{[Name="NBA_Project"]}[Data],
				    analytics_vw_q7_balance_of_def = NBA_Project{[Schema="analytics",Item="vw_q7_balance_of_def"]}[Data],
				    #"Columnas con nombre cambiado" = Table.RenameColumns(analytics_vw_q7_balance_of_def,{{"fg_pct_avg", "Eficiencia de tiro"}, {"tov_avg", "Balones perdidos"}})
				in
				    #"Columnas con nombre cambiado"

