/* GENERATED by scripts/generate_model_artifacts.py. Do not edit manually. */
/* Contract schema: 1.0.0 */
SET NOCOUNT ON;
SET XACT_ABORT ON;
GO
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = N'core') EXEC(N'CREATE SCHEMA core');
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = N'analytics') EXEC(N'CREATE SCHEMA analytics');
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = N'audit') EXEC(N'CREATE SCHEMA audit');
GO
IF OBJECT_ID(N'core.dim_team', N'U') IS NULL
BEGIN
    CREATE TABLE [core].[dim_team] (
        [team_id] BIGINT NOT NULL,
        [full_name] NVARCHAR(255) NOT NULL,
        [abbreviation] NVARCHAR(255) NOT NULL,
        [nickname] NVARCHAR(255) NULL,
        [city] NVARCHAR(255) NULL,
        [state] NVARCHAR(255) NULL,
        [year_founded] INT NULL,
        [is_historical_unmapped] BIT NOT NULL,
        CONSTRAINT [PK_dim_team_team_id] PRIMARY KEY ([team_id])
    );
END;
GO
IF OBJECT_ID(N'core.dim_player', N'U') IS NULL
BEGIN
    CREATE TABLE [core].[dim_player] (
        [player_id] BIGINT NOT NULL,
        [full_name] NVARCHAR(255) NOT NULL,
        [first_name] NVARCHAR(255) NULL,
        [last_name] NVARCHAR(255) NOT NULL,
        [is_active] BIT NOT NULL,
        CONSTRAINT [PK_dim_player_player_id] PRIMARY KEY ([player_id])
    );
END;
GO
IF OBJECT_ID(N'core.fact_game', N'U') IS NULL
BEGIN
    CREATE TABLE [core].[fact_game] (
        [season_id] INT NOT NULL,
        [team_id_home] BIGINT NOT NULL,
        [team_abbreviation_home] NVARCHAR(255) NOT NULL,
        [team_name_home] NVARCHAR(255) NOT NULL,
        [game_id] BIGINT NOT NULL,
        [game_date] DATE NOT NULL,
        [matchup_home] NVARCHAR(255) NOT NULL,
        [wl_home] NVARCHAR(255) NULL,
        [min] INT NOT NULL,
        [fgm_home] FLOAT NULL,
        [fga_home] FLOAT NULL,
        [fg_pct_home] FLOAT NULL,
        [fg3m_home] FLOAT NULL,
        [fg3a_home] FLOAT NULL,
        [fg3_pct_home] FLOAT NULL,
        [ftm_home] FLOAT NULL,
        [fta_home] FLOAT NULL,
        [ft_pct_home] FLOAT NULL,
        [oreb_home] FLOAT NULL,
        [dreb_home] FLOAT NULL,
        [reb_home] FLOAT NULL,
        [ast_home] FLOAT NULL,
        [stl_home] FLOAT NULL,
        [blk_home] FLOAT NULL,
        [tov_home] FLOAT NULL,
        [pf_home] FLOAT NULL,
        [pts_home] FLOAT NULL,
        [plus_minus_home] FLOAT NULL,
        [video_available_home] BIT NOT NULL,
        [team_id_away] BIGINT NOT NULL,
        [team_abbreviation_away] NVARCHAR(255) NOT NULL,
        [team_name_away] NVARCHAR(255) NOT NULL,
        [matchup_away] NVARCHAR(255) NOT NULL,
        [wl_away] NVARCHAR(255) NULL,
        [fgm_away] FLOAT NULL,
        [fga_away] FLOAT NULL,
        [fg_pct_away] FLOAT NULL,
        [fg3m_away] FLOAT NULL,
        [fg3a_away] FLOAT NULL,
        [fg3_pct_away] FLOAT NULL,
        [ftm_away] FLOAT NULL,
        [fta_away] FLOAT NULL,
        [ft_pct_away] FLOAT NULL,
        [oreb_away] FLOAT NULL,
        [dreb_away] FLOAT NULL,
        [reb_away] FLOAT NULL,
        [ast_away] FLOAT NULL,
        [stl_away] FLOAT NULL,
        [blk_away] FLOAT NULL,
        [tov_away] FLOAT NULL,
        [pf_away] FLOAT NULL,
        [pts_away] FLOAT NULL,
        [plus_minus_away] FLOAT NULL,
        [video_available_away] BIT NOT NULL,
        [season_type] NVARCHAR(255) NOT NULL,
        [season_year] INT NOT NULL,
        [season_stage] NVARCHAR(255) NOT NULL,
        CONSTRAINT [PK_fact_game_game_id] PRIMARY KEY ([game_id])
    );
END;
GO
IF OBJECT_ID(N'core.dim_player_profile', N'U') IS NULL
BEGIN
    CREATE TABLE [core].[dim_player_profile] (
        [player_id] BIGINT NOT NULL,
        [first_name] NVARCHAR(255) NULL,
        [last_name] NVARCHAR(255) NOT NULL,
        [display_first_last] NVARCHAR(255) NOT NULL,
        [display_last_comma_first] NVARCHAR(255) NOT NULL,
        [display_fi_last] NVARCHAR(255) NOT NULL,
        [player_slug] NVARCHAR(255) NOT NULL,
        [birthdate] DATE NOT NULL,
        [school] NVARCHAR(255) NULL,
        [country] NVARCHAR(255) NULL,
        [last_affiliation] NVARCHAR(255) NOT NULL,
        [height] NVARCHAR(255) NULL,
        [weight] FLOAT NULL,
        [season_exp] INT NOT NULL,
        [jersey] NVARCHAR(255) NULL,
        [position] NVARCHAR(255) NULL,
        [rosterstatus] NVARCHAR(255) NOT NULL,
        [games_played_current_season_flag] BIT NOT NULL,
        [team_id] BIGINT NULL,
        [team_name] NVARCHAR(255) NULL,
        [team_abbreviation] NVARCHAR(255) NULL,
        [team_code] NVARCHAR(255) NULL,
        [team_city] NVARCHAR(255) NULL,
        [playercode] NVARCHAR(255) NULL,
        [from_year] INT NULL,
        [to_year] INT NULL,
        [dleague_flag] BIT NOT NULL,
        [nba_flag] BIT NOT NULL,
        [games_played_flag] BIT NOT NULL,
        [draft_year] INT NULL,
        [draft_round] NVARCHAR(255) NULL,
        [draft_number] NVARCHAR(255) NULL,
        [greatest_75_flag] BIT NOT NULL,
        [height_inches] FLOAT NULL,
        [height_cm] FLOAT NULL,
        CONSTRAINT [PK_dim_player_profile_player_id] PRIMARY KEY ([player_id])
    );
END;
GO
IF OBJECT_ID(N'core.fact_game_summary', N'U') IS NULL
BEGIN
    CREATE TABLE [core].[fact_game_summary] (
        [game_date_est] DATE NOT NULL,
        [game_sequence] INT NULL,
        [game_id] BIGINT NOT NULL,
        [game_status_id] INT NOT NULL,
        [game_status_text] NVARCHAR(255) NULL,
        [gamecode] NVARCHAR(255) NOT NULL,
        [home_team_id] BIGINT NOT NULL,
        [visitor_team_id] BIGINT NOT NULL,
        [season_year] INT NOT NULL,
        [live_period] INT NOT NULL,
        [live_pc_time] NVARCHAR(255) NULL,
        [natl_tv_broadcaster_abbreviation] NVARCHAR(255) NULL,
        [live_period_time_bcast] NVARCHAR(255) NULL,
        [wh_status] INT NOT NULL,
        CONSTRAINT [PK_fact_game_summary_game_id] PRIMARY KEY ([game_id])
    );
END;
GO
IF OBJECT_ID(N'core.fact_other_stats', N'U') IS NULL
BEGIN
    CREATE TABLE [core].[fact_other_stats] (
        [game_id] BIGINT NOT NULL,
        [league_id] INT NOT NULL,
        [team_id_home] BIGINT NOT NULL,
        [team_abbreviation_home] NVARCHAR(255) NOT NULL,
        [team_city_home] NVARCHAR(255) NOT NULL,
        [pts_paint_home] FLOAT NULL,
        [pts_2nd_chance_home] FLOAT NULL,
        [pts_fb_home] FLOAT NULL,
        [largest_lead_home] FLOAT NULL,
        [lead_changes] FLOAT NULL,
        [times_tied] FLOAT NULL,
        [team_turnovers_home] FLOAT NULL,
        [total_turnovers_home] FLOAT NULL,
        [team_rebounds_home] FLOAT NULL,
        [pts_off_to_home] FLOAT NULL,
        [team_id_away] BIGINT NOT NULL,
        [team_abbreviation_away] NVARCHAR(255) NOT NULL,
        [team_city_away] NVARCHAR(255) NOT NULL,
        [pts_paint_away] FLOAT NULL,
        [pts_2nd_chance_away] FLOAT NULL,
        [pts_fb_away] FLOAT NULL,
        [largest_lead_away] FLOAT NULL,
        [team_turnovers_away] FLOAT NULL,
        [total_turnovers_away] FLOAT NULL,
        [team_rebounds_away] FLOAT NULL,
        [pts_off_to_away] FLOAT NULL,
        CONSTRAINT [PK_fact_other_stats_game_id] PRIMARY KEY ([game_id])
    );
END;
GO
IF OBJECT_ID(N'audit.etl_run', N'U') IS NULL
BEGIN
    CREATE TABLE [audit].[etl_run] (
        [run_id] NVARCHAR(64) NOT NULL CONSTRAINT [PK_etl_run] PRIMARY KEY,
        [schema_version] NVARCHAR(20) NOT NULL,
        [started_at_utc] DATETIME2 NOT NULL,
        [loaded_at_utc] DATETIME2 NOT NULL CONSTRAINT [DF_etl_run_loaded] DEFAULT SYSUTCDATETIME(),
        [status] NVARCHAR(20) NOT NULL,
        [input_rows] BIGINT NOT NULL,
        [output_rows] BIGINT NOT NULL,
        [rejected_rows] BIGINT NOT NULL
    );
END;
GO
IF OBJECT_ID(N'audit.table_reconciliation', N'U') IS NULL
BEGIN
    CREATE TABLE [audit].[table_reconciliation] (
        [run_id] NVARCHAR(64) NOT NULL,
        [table_name] NVARCHAR(128) NOT NULL,
        [input_rows] BIGINT NOT NULL,
        [accepted_rows] BIGINT NOT NULL,
        [generated_rows] BIGINT NOT NULL,
        [rejected_rows] BIGINT NOT NULL,
        [loaded_rows] BIGINT NOT NULL,
        CONSTRAINT [PK_table_reconciliation] PRIMARY KEY ([run_id], [table_name]),
        CONSTRAINT [FK_table_reconciliation_run] FOREIGN KEY ([run_id]) REFERENCES [audit].[etl_run]([run_id])
    );
END;
GO
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_dim_player_profile_player_id')
BEGIN
    ALTER TABLE [core].[dim_player_profile] WITH CHECK
    ADD CONSTRAINT [FK_dim_player_profile_player_id] FOREIGN KEY ([player_id])
    REFERENCES [core].[dim_player] ([player_id]);
END;
GO
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_dim_player_profile_team_id')
BEGIN
    ALTER TABLE [core].[dim_player_profile] WITH CHECK
    ADD CONSTRAINT [FK_dim_player_profile_team_id] FOREIGN KEY ([team_id])
    REFERENCES [core].[dim_team] ([team_id]);
END;
GO
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_game_team_id_home')
BEGIN
    ALTER TABLE [core].[fact_game] WITH CHECK
    ADD CONSTRAINT [FK_fact_game_team_id_home] FOREIGN KEY ([team_id_home])
    REFERENCES [core].[dim_team] ([team_id]);
END;
GO
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_game_team_id_away')
BEGIN
    ALTER TABLE [core].[fact_game] WITH CHECK
    ADD CONSTRAINT [FK_fact_game_team_id_away] FOREIGN KEY ([team_id_away])
    REFERENCES [core].[dim_team] ([team_id]);
END;
GO
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_game_summary_game_id')
BEGIN
    ALTER TABLE [core].[fact_game_summary] WITH CHECK
    ADD CONSTRAINT [FK_fact_game_summary_game_id] FOREIGN KEY ([game_id])
    REFERENCES [core].[fact_game] ([game_id]);
END;
GO
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_game_summary_home_team_id')
BEGIN
    ALTER TABLE [core].[fact_game_summary] WITH CHECK
    ADD CONSTRAINT [FK_fact_game_summary_home_team_id] FOREIGN KEY ([home_team_id])
    REFERENCES [core].[dim_team] ([team_id]);
END;
GO
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_game_summary_visitor_team_id')
BEGIN
    ALTER TABLE [core].[fact_game_summary] WITH CHECK
    ADD CONSTRAINT [FK_fact_game_summary_visitor_team_id] FOREIGN KEY ([visitor_team_id])
    REFERENCES [core].[dim_team] ([team_id]);
END;
GO
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_other_stats_game_id')
BEGIN
    ALTER TABLE [core].[fact_other_stats] WITH CHECK
    ADD CONSTRAINT [FK_fact_other_stats_game_id] FOREIGN KEY ([game_id])
    REFERENCES [core].[fact_game] ([game_id]);
END;
GO
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_other_stats_team_id_home')
BEGIN
    ALTER TABLE [core].[fact_other_stats] WITH CHECK
    ADD CONSTRAINT [FK_fact_other_stats_team_id_home] FOREIGN KEY ([team_id_home])
    REFERENCES [core].[dim_team] ([team_id]);
END;
GO
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_other_stats_team_id_away')
BEGIN
    ALTER TABLE [core].[fact_other_stats] WITH CHECK
    ADD CONSTRAINT [FK_fact_other_stats_team_id_away] FOREIGN KEY ([team_id_away])
    REFERENCES [core].[dim_team] ([team_id]);
END;
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_fact_game_season_year' AND object_id = OBJECT_ID(N'core.fact_game'))
    CREATE INDEX [IX_fact_game_season_year] ON [core].[fact_game] ([season_year]);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_fact_game_team_id_home' AND object_id = OBJECT_ID(N'core.fact_game'))
    CREATE INDEX [IX_fact_game_team_id_home] ON [core].[fact_game] ([team_id_home]);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_fact_game_team_id_away' AND object_id = OBJECT_ID(N'core.fact_game'))
    CREATE INDEX [IX_fact_game_team_id_away] ON [core].[fact_game] ([team_id_away]);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_dim_player_profile_team_id' AND object_id = OBJECT_ID(N'core.dim_player_profile'))
    CREATE INDEX [IX_dim_player_profile_team_id] ON [core].[dim_player_profile] ([team_id]);
GO
