"""Generate the committed contract, canonical DDL and data dictionary."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from nba_pipeline.contracts import OUTPUT_SPECS, SCHEMA_VERSION, contract_bundle  # noqa: E402
from nba_pipeline.utils import json_bytes  # noqa: E402

LOAD_ORDER = (
    "dim_team",
    "dim_player",
    "fact_game",
    "dim_player_profile",
    "fact_game_summary",
    "fact_other_stats",
)


def sql_type(name: str, dtype: str) -> str:
    if dtype == "integer":
        return "BIGINT" if name in {"game_id", "player_id"} or "team_id" in name else "INT"
    if dtype == "float":
        return "FLOAT"
    if dtype == "boolean":
        return "BIT"
    if dtype == "date":
        return "DATE"
    if dtype == "string":
        return "NVARCHAR(255)"
    raise ValueError(f"Unsupported SQL type: {dtype}")


def output_columns(output_name: str):
    spec = OUTPUT_SPECS[output_name]
    for column in (*spec.columns, *spec.derived_columns):
        yield column.canonical_name, column


def bracket(name: str) -> str:
    return f"[{name}]"


def constraint_name(prefix: str, table: str, columns: tuple[str, ...]) -> str:
    return f"{prefix}_{table}_{'_'.join(columns)}"


def generate_ddl() -> str:
    lines = [
        "/* GENERATED by scripts/generate_model_artifacts.py. Do not edit manually. */",
        f"/* Contract schema: {SCHEMA_VERSION} */",
        "SET NOCOUNT ON;",
        "SET XACT_ABORT ON;",
        "GO",
        "IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = N'core') EXEC(N'CREATE SCHEMA core');",
        "IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = N'analytics') EXEC(N'CREATE SCHEMA analytics');",
        "IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = N'audit') EXEC(N'CREATE SCHEMA audit');",
        "GO",
    ]
    for output_name in LOAD_ORDER:
        spec = OUTPUT_SPECS[output_name]
        schema, table = spec.sql_table.split(".")
        columns = list(output_columns(output_name))
        definitions = []
        for name, column in columns:
            nullable = "NULL" if column.nullable else "NOT NULL"
            definitions.append(f"        {bracket(name)} {sql_type(name, column.dtype)} {nullable}")
        pk = ", ".join(bracket(name) for name in spec.output_primary_key)
        definitions.append(
            f"        CONSTRAINT {bracket(constraint_name('PK', table, spec.output_primary_key))} PRIMARY KEY ({pk})"
        )
        lines.extend(
            [
                f"IF OBJECT_ID(N'{schema}.{table}', N'U') IS NULL",
                "BEGIN",
                f"    CREATE TABLE {bracket(schema)}.{bracket(table)} (",
                ",\n".join(definitions),
                "    );",
                "END;",
                "GO",
            ]
        )

    lines.extend(
        [
            "IF OBJECT_ID(N'audit.etl_run', N'U') IS NULL",
            "BEGIN",
            "    CREATE TABLE [audit].[etl_run] (",
            "        [run_id] NVARCHAR(64) NOT NULL CONSTRAINT [PK_etl_run] PRIMARY KEY,",
            "        [schema_version] NVARCHAR(20) NOT NULL,",
            "        [started_at_utc] DATETIME2 NOT NULL,",
            "        [loaded_at_utc] DATETIME2 NOT NULL CONSTRAINT [DF_etl_run_loaded] DEFAULT SYSUTCDATETIME(),",
            "        [status] NVARCHAR(20) NOT NULL,",
            "        [input_rows] BIGINT NOT NULL,",
            "        [output_rows] BIGINT NOT NULL,",
            "        [rejected_rows] BIGINT NOT NULL",
            "    );",
            "END;",
            "GO",
            "IF OBJECT_ID(N'audit.table_reconciliation', N'U') IS NULL",
            "BEGIN",
            "    CREATE TABLE [audit].[table_reconciliation] (",
            "        [run_id] NVARCHAR(64) NOT NULL,",
            "        [table_name] NVARCHAR(128) NOT NULL,",
            "        [input_rows] BIGINT NOT NULL,",
            "        [accepted_rows] BIGINT NOT NULL,",
            "        [generated_rows] BIGINT NOT NULL,",
            "        [rejected_rows] BIGINT NOT NULL,",
            "        [loaded_rows] BIGINT NOT NULL,",
            "        CONSTRAINT [PK_table_reconciliation] PRIMARY KEY ([run_id], [table_name]),",
            "        CONSTRAINT [FK_table_reconciliation_run] FOREIGN KEY ([run_id]) REFERENCES [audit].[etl_run]([run_id])",
            "    );",
            "END;",
            "GO",
        ]
    )

    foreign_keys = (
        ("dim_player_profile", ("player_id",), "dim_player", ("player_id",)),
        ("dim_player_profile", ("team_id",), "dim_team", ("team_id",)),
        ("fact_game", ("team_id_home",), "dim_team", ("team_id",)),
        ("fact_game", ("team_id_away",), "dim_team", ("team_id",)),
        ("fact_game_summary", ("game_id",), "fact_game", ("game_id",)),
        ("fact_game_summary", ("home_team_id",), "dim_team", ("team_id",)),
        ("fact_game_summary", ("visitor_team_id",), "dim_team", ("team_id",)),
        ("fact_other_stats", ("game_id",), "fact_game", ("game_id",)),
        ("fact_other_stats", ("team_id_home",), "dim_team", ("team_id",)),
        ("fact_other_stats", ("team_id_away",), "dim_team", ("team_id",)),
    )
    for child, child_cols, parent, parent_cols in foreign_keys:
        name = constraint_name("FK", child, child_cols)
        nullable_fk = child == "dim_player_profile" and child_cols == ("team_id",)
        lines.extend(
            [
                f"IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'{name}')",
                "BEGIN",
                f"    ALTER TABLE [core].{bracket(child)} WITH CHECK",
                f"    ADD CONSTRAINT {bracket(name)} FOREIGN KEY ({', '.join(bracket(c) for c in child_cols)})",
                f"    REFERENCES [core].{bracket(parent)} ({', '.join(bracket(c) for c in parent_cols)});",
                "END;",
                "GO",
            ]
        )
        if nullable_fk:
            continue

    indexes = (
        ("fact_game", "season_year"),
        ("fact_game", "team_id_home"),
        ("fact_game", "team_id_away"),
        ("dim_player_profile", "team_id"),
    )
    for table, column in indexes:
        name = f"IX_{table}_{column}"
        lines.extend(
            [
                f"IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'{name}' AND object_id = OBJECT_ID(N'core.{table}'))",
                f"    CREATE INDEX {bracket(name)} ON [core].{bracket(table)} ({bracket(column)});",
                "GO",
            ]
        )
    return "\n".join(lines) + "\n"


def generate_dictionary() -> str:
    lines = [
        "# Canonical data dictionary — NBA-I1–I3",
        "",
        f"Contract version: `{SCHEMA_VERSION}`.",
        "",
        "This file is generated from `src/nba_pipeline/contracts.py`. Nullable historical",
        "statistics remain null; they are not imputed as zero.",
        "",
    ]
    for output_name in LOAD_ORDER:
        spec = OUTPUT_SPECS[output_name]
        lines.extend(
            [
                f"## `{spec.sql_table}` / `{output_name}.csv`",
                "",
                spec.description,
                "",
                "| Column | Type | Nullable | Rule |",
                "|---|---|---:|---|",
            ]
        )
        for name, column in output_columns(output_name):
            rules = []
            if column.allowed:
                rules.append("domain=" + ", ".join(str(value) for value in column.allowed))
            if column.minimum is not None:
                rules.append(f"min={column.minimum:g}")
            if column.maximum is not None:
                rules.append(f"max={column.maximum:g}")
            if name in spec.output_primary_key:
                rules.append("primary key")
            lines.append(
                f"| `{name}` | `{column.dtype}` | {'yes' if column.nullable else 'no'} | "
                f"{'<br>'.join(rules) or '—'} |"
            )
        lines.append("")
    return "\n".join(lines)


def artifacts() -> dict[Path, bytes]:
    return {
        ROOT / "contracts" / f"schema_v{SCHEMA_VERSION}.json": json_bytes(contract_bundle()),
        ROOT / "CODE" / "SQL" / "10_core_schema.sql": generate_ddl().encode("utf-8"),
        ROOT / "DOCS" / "canonical_data_dictionary.md": generate_dictionary().encode("utf-8"),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    failures = []
    for path, expected in artifacts().items():
        if args.check:
            if not path.exists() or path.read_bytes() != expected:
                failures.append(path.relative_to(ROOT).as_posix())
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(expected)
            print(path.relative_to(ROOT).as_posix())
    if failures:
        print("Generated artifacts are stale: " + ", ".join(failures), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
